import express from 'express';
import { upload } from '../configs/multer.js';
import { authSeller } from '../middlewares/authSeller.js';
import { addProduct, productById, productList, changeStock } from '../controller/productcontroller.js';
const productRouter = express.Router();
productRouter.post('/add', upload.array("images", 4), authSeller, addProduct);
productRouter.get('/list', productList);
productRouter.get('/list/:id', productById);
productRouter.post('/change-stock', authSeller, changeStock);
export default productRouter;